dist: xenial
language: python
python:
  - 3.6
  - 3.7
  - 3.8.2
  - nightly
matrix:
  allow_failures:
    - python: nightly
  include:
    - python: 3.8
      env: TOXENV=py38-coverage
install:
    - pip install --quiet tox-travis
script:
    - tox
after_script:
    - |
      if [ "${TOXENV%-coverage}" == "$TOXENV" ]; then
        pip install --quiet coveralls;
        coveralls;
      fi
